name: Index Med Vitrina24

on:
  schedule:
    - cron: '30 3 * * *'  # Запуск в 03:30 UTC каждый день
    - cron: '30 15 * * *' # Запуск в 15:30 UTC каждый день
  workflow_dispatch:

permissions:
  contents: write

jobs:
  index_med_vitrina:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Create data directory
        run: mkdir -p data

      - name: Run Med Vitrina Indexing
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          MEDVITRINA24KZ_CREDENTIALS: ${{ secrets.MEDVITRINA24KZ_CREDENTIALS }}
        run: python scripts/index_med_vitrina.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/
          git commit -m 'Update index files for med.vitrina24.kz'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
