name: Daily Indexing

on:
  schedule:
    - cron: "0 15 * * *"
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TGTOKENVITRINA24KZ }}
      VITRINA24KZ_CREDENTIALS: ${{ secrets.VITRINA24KZ82FD975FBBE4 }}
      MEDVITRINA24KZ_CREDENTIALS: ${{ secrets.MEDVITRINA24KZ61856B49EC6E }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Send start notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TGTOKENVITRINA24KZ }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Indexing process started for vitrina24.kz and med.vitrina24.kz"

      - name: Start indexing process
        run: |
          python scripts/indexer.py

      - name: Check quota and issues
        run: |
          python scripts/check_quota_and_issues.py

      - name: Send completion notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TGTOKENVITRINA24KZ }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Indexing process completed"
